solution 1
mmikolajewski/Household_budget_DAO pull request #1
Opened 2023-04-30 18:08 UTC by mmikolajewski

2023-05-01 08:28 UTC, slawekludwiczak requested changes
katalogu idea nie dodawaj w przyszłości w commitach (najlepiej dodać go w gitignore)

2023-05-01 08:28 UTC, slawekludwiczak commented on src/main/java/com/cash/app/HouseHoldControl.java
> +    DataReaderPrinter dataReaderPrinter = new DataReaderPrinter();
private

2023-05-01 08:28 UTC, slawekludwiczak commented on src/main/java/com/cash/io/TransactionDao.java
> +            }
To można wydzielić do osobnej metody, kod powtarza się w transactionsByType()

2023-05-01 08:28 UTC, slawekludwiczak commented on src/main/java/com/cash/io/TransactionDao.java
> +                System.out.println(transaction);
W DAO nie powinieneś nic wyświetlać, zamiast tego metoda powinna zwrócić listę `List<Transaction>`, a wyświetlaniem powinieneś się zająć poziom wyżej

2023-05-01 08:28 UTC, slawekludwiczak commented on src/main/java/com/cash/io/TransactionDao.java
> +                System.out.println(transaction);
W DAO nie powinieneś nic wyświetlać, zamiast tego metoda powinna zwrócić listę `List<Transaction>`, a wyświetlaniem powinieneś się zająć poziom wyżej

2023-05-01 08:28 UTC, slawekludwiczak commented on src/main/java/com/cash/app/MainOption.java
> +    ADD_TRANSACTION(1, "Dodanie tranzakcji"),
tranSakcja

2023-05-01 08:28 UTC, slawekludwiczak commented on src/main/java/com/cash/io/DataReaderPrinter.java
> +        String type = getType();
koszt = wydatek, tutaj raczej powinno być pytanie o opis i typ transakcji

2023-05-01 21:01 UTC, mmikolajewski commented
coś zepsułem z ignorowaniem pliku .idea, ale nadrobię to przy następnym zadaniu.

2023-05-02 15:29 UTC, marcinkunert approved these changes

2023-08-13 18:04 UTC, merged